- name: Install kubectl
  shell: |
    set -ex

    if [ ! -e /bin/kubectl ]
    then
      cd /bin
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod 755 kubectl
    fi
- name: Install golang
  apt:
    name: golang
    state: present

- name: Install kind
  shell: go install sigs.k8s.io/kind@latest

- name: Initialize cluster
  shell: |
    if ! docker ps | grep -q {{ HOST_DNS_NAME }}-control-plane
    then
      $(go env GOPATH)/bin/kind create cluster --name {{ HOST_DNS_NAME }}
    fi

- import_tasks: install_traefik.yml

- import_tasks: install_k8s_services.yml

- import_tasks: install_networking.yml

- import_tasks: print_info.yml