stages:
  - create
  - provision
  - destroy

variables:
  PROJECT_SERVER_NAME:
    description: "Name of node in the system like 'k8s', this will appear in domain like k8s.ecorp.intra.net"
  PROJECT_TYPE:
    description: "Type of new system: proxmox, systemd, docker, kubernetes"
  PROJECT_NETWORK_ROUTE:
    description: "Extra route controller should add to the core network, making project server internal machines accessible via routing. eg: 192.168.15.0/24"
  PROJECT_DNS_MODE:
    description: "DNS mode of the project: static (*.name resolved to node), delegated (dns forwarded for this server, for routed networks)"
    value: static

  BUILD_IMAGE: build-image:latest
  ECORP_CORE_NETWORK_BRIDGE: ecorp_core

custom-create:
  stage: create
  image: $BUILD_IMAGE
  when: manual
  tags:
    - core
  script: ./project-server create

custom-provision:
  stage: provision
  image: $BUILD_IMAGE
  when: manual
  tags:
    - core
  script: ./project-server provision

custom-destroy:
  stage: destroy
  image: $BUILD_IMAGE
  when: manual
  tags:
    - core
  script: ./project-server destroy

kubernetes-create:
  extends: custom-create
  variables:
    PROJECT_SERVER_NAME: k8s
    PROJECT_DNS_MODE: kubernetes

kubernetes-provision:
  extends: custom-provision
  variables:
    PROJECT_SERVER_NAME: kx
    PROJECT_DNS_MODE: kubernetes

kubernetes-destroy:
  extends: custom-destroy
  variables:
    PROJECT_SERVER_NAME: kx
    PROJECT_DNS_MODE: kubernetes

docker-create:
  extends: custom-create
  variables:
    PROJECT_SERVER_NAME: dx
    PROJECT_DNS_MODE: docker

docker-provision:
  extends: custom-provision
  variables:
    PROJECT_SERVER_NAME: dx
    PROJECT_DNS_MODE: docker

docker-destroy:
  extends: custom-destroy
  variables:
    PROJECT_SERVER_NAME: dx
    PROJECT_DNS_MODE: docker

proxmox-create:
  extends: custom-create
  variables:
    PROJECT_SERVER_NAME: px
    PROJECT_DNS_MODE: proxmox

proxmox-provision:
  extends: custom-provision
  variables:
    PROJECT_SERVER_NAME: px
    PROJECT_DNS_MODE: proxmox

proxmox-destroy:
  extends: custom-destroy
  variables:
    PROJECT_SERVER_NAME: px
    PROJECT_DNS_MODE: proxmox