stages:
  - create
  - provision
  - destroy

variables:
  PROJECT_SERVER_NAME:
    description: "Name of node in the system like 'k8s', this will appear in domain like k8s.ecorp.intra.net"
  PROJECT_TYPE:
    description: "Type of new system: proxmox, systemd, docker, kubernetes"
  PROJECT_NETWORK_ROUTE:
    description: "Extra route controller should add to the core network, making project server internal machines accessible via routing. eg: 192.168.15.0/24"
  PROJECT_NETWORK_SIZE:
    description: "only if PROJECT_NETWORK_ROUTE specified. Specifiy the docker subnet size, eg.: /26 (make at least two times smaller than specified in route)"
    value: "26"
  PROJECT_DNS_MODE:
    description: "DNS mode of the project: static (*.name resolved to node), delegated (dns forwarded for this server, for routed networks)"
    value: static
  GITLAB_RUNNER_TOKEN:
    description: "If set, register a gitlab runner (in docker based) project server"
  SERVICE_DISCOVERY_PORT:
    description: "If specified, a service listing application is installed (on docker based) containers on the given port (eg 900)"

  BUILD_IMAGE: devops-build-image:latest

custom-create:
  stage: create
  image: $BUILD_IMAGE
  when: manual
  tags:
    - core
  script: ./project-server create

custom-provision:
  stage: provision
  image: $BUILD_IMAGE
  when: manual
  tags:
    - core
  script: ./project-server provision

custom-destroy:
  stage: destroy
  image: $BUILD_IMAGE
  when: manual
  tags:
    - core
  script: ./project-server destroy

kubernetes-create:
  extends: custom-create
  variables:
    PROJECT_SERVER_NAME: kx
    PROJECT_TYPE: kubernetes

kubernetes-provision:
  extends: custom-provision
  variables:
    PROJECT_SERVER_NAME: kx
    PROJECT_TYPE: kubernetes

kubernetes-destroy:
  extends: custom-destroy
  variables:
    PROJECT_SERVER_NAME: kx
    PROJECT_TYPE: kubernetes

docker-create:
  extends: custom-create
  variables:
    PROJECT_SERVER_NAME: dx
    PROJECT_TYPE: docker

docker-provision:
  extends: custom-provision
  variables:
    PROJECT_SERVER_NAME: dx
    PROJECT_TYPE: docker

docker-destroy:
  extends: custom-destroy
  variables:
    PROJECT_SERVER_NAME: dx
    PROJECT_TYPE: docker

proxmox-create:
  extends: custom-create
  variables:
    PROJECT_SERVER_NAME: px
    PROJECT_TYPE: proxmox

proxmox-provision:
  extends: custom-provision
  variables:
    PROJECT_SERVER_NAME: px
    PROJECT_TYPE: proxmox

proxmox-destroy:
  extends: custom-destroy
  variables:
    PROJECT_SERVER_NAME: px
    PROJECT_TYPE: proxmox
