targets:
  hosts:
    target:
      DNS_CORE_ZONE_NAME: "{{ lookup('env', 'DNS_CORE_ZONE_NAME') }}"
      PROJECT_SERVER_NAME: "{{ lookup('env', 'PROJECT_SERVER_NAME') }}"

      ansible_user: root
      ansible_host: "{{ PROJECT_SERVER_NAME }}.{{ DNS_CORE_ZONE_NAME }}"
      ansible_password: password


