targets:
  hosts:
    target:
      ECORP_DNS_CORE_ZONE_NAME: "{{ lookup('env', 'ECORP_DNS_CORE_ZONE_NAME') }}"
      PROJECT_SERVER_NAME: "{{ lookup('env', 'PROJECT_SERVER_NAME') }}"
      HOST_DNS_NAME: "{{ PROJECT_SERVER_NAME }}.{{ ECORP_DNS_CORE_ZONE_NAME }}"

      PROJECT_NETWORK_ROUTE: "{{ lookup('env', 'PROJECT_NETWORK_ROUTE') }}"
      PROJECT_NETWORK_SIZE: "{{ lookup('env', 'PROJECT_NETWORK_SIZE') }}"
      PROJECT_DNS_MODE: "{{ lookup('env', 'PROJECT_DNS_MODE') }}"
      GITLAB_RUNNER_TOKEN: "{{ lookup('env', 'GITLAB_RUNNER_TOKEN') }}"
      SERVICE_DISCOVERY_PORT: "{{ lookup('env', 'SERVICE_DISCOVERY_PORT') | default('') }}"

      ECORP_SSH_EXTRA_AUTH: "{{ lookup('env', 'ECORP_SSH_EXTRA_AUTH') }}"

      ansible_user: root
      ansible_host: "{{ HOST_DNS_NAME }}"
      ansible_password: password


