- name: Configure containerd
  template:
    src: containerd.toml
    dest: /etc/containerd/config.toml
  register: containerd
  
- name: Configure docker
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config

# Enable containerd
- name: Enable containerd and start immediately
  service:
    name: containerd
    daemon_reload: yes
    state: "{{ 'restarted' if containerd.changed else 'started' }}"
    enabled: yes

# Enable docker
- name: Enable docker and start immediately
  service:
    name: docker
    daemon_reload: yes
    state: "{{ 'restarted' if docker_config.changed else 'started' }}"
    enabled: yes

- name: Register project runner
  include_tasks: register_project_runner.yml

- name: Launch project server service
  include_tasks: project_server_service.yml
  when: PROJECT_DNS_MODE == 'delegated' or (SERVICE_DISCOVERY_PORT | default('')) != ''

